### ISSUE TITLE
Statusline is incorrect after upgrading to 0.3.0

### ISSUE THREAD

**Issue by bwbuhse** [catppuccin/tmux#330]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

The status line is missing the right-hand side modules, as well as process names for tabs.

### Paste your configuration.

```sh
unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind -n C-k clear-history

set-option -g set-titles on
set-option -g set-titles-string "#S / #W"

# set term to tmux instead of gnu screen
# this enables proper italics support
set -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "tmux-256color"

setw -g mode-keys vi
set -g mouse on

set-option -g status-position bottom

set -g @catppuccin_flavor 'mocha'
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# List of TPM-managaed plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.config/tmux/plugins/tpm/tpm'
```

### Attach screenshots.

![Screenshot](https://github.com/user-attachments/assets/fe4066b6-a854-4c2d-b53c-b8e02d36a7cf)

### What tmux version are you seeing the issue on?

tmux 3.4 and tmux 3.5

**Comment by av1155** [comment]
Same here, and my tmux does not want to install cattpuccin via tpm

**Comment by mauromotion** [comment]
Same here, I tried both with and without tpm. With tpm it was like nothing was updated, although it said "updated". Without I could see some differences as in stuff got broken, and some new settings are just doing nothing at all.

**Comment by davidfmatheson** [comment]
I had this problem after updating to 0.3.0, I had to run this task (your location may vary):

```bash
$ ~/.config/tmux/plugins/tpm/bin/clean_plugins
```

After restarting it refreshed the plugins and things were back to normal (thanks to continuum and resurrect plugins).

**Comment by kjnsn** [comment]
Thanks so much for upgrading! I've updated the readme to include some notes regarding the upgrade. v0.4.0 should have fixed the `#T` appearing in the window formats

**Comment by mauromotion** [comment]
Well now after cleaning running the script that @davidfmatheson  mentioned, I can see the update with TPM. Nonetheless it's still not working correctly for me. In the screenshot you can see my tmux/catppuccin config lines and the actual tmux bar. It's on a transparent background but anyway, all the elements in the bar look kinda wrong.

![tmux_catppuccin_bugs](https://github.com/user-attachments/assets/bee13c75-0cb6-41ac-b606-207f391c78db)

**Comment by kjnsn** [comment]
Yep that's the default! Although it's odd that the current window style isn't rounded.

Can you explain what you mean by "kinda wrong"? What is the expected behaviour?

**Comment by mauromotion** [comment]
It looks broken? As in, why only the windows are styled? The rest of the bar is just default tmux with a different bg colour. With the previous version of this plugin I had a different default without customising anything (which doesn't mean I liked it, but anyway). 

But if you can confirm this is the "default" look and set up, I can work from here. It's just a weird first experience for a user maybe? It looks inconsistent, half/done half/broken. But maybe it's just me, just my 2 cents. 

I can go on and customise it now (after I figured out why the selected window is squared maybe). Thanks!

**Comment by kjnsn** [comment]
>  (which doesn't mean I liked it, but anyway).

Yeah this was a big reason for changing the defaults.

> But if you can confirm this is the "default" look and set up, I can work from here.

This is the default look and setup currently.

> It's just a weird first experience for a user maybe? It looks inconsistent, half/done half/broken. But maybe it's just me, just my 2 cents.

That's really helpful feedback! I'd be keen to provide some sensible defaults (the current ones could be improved), at least with the initial configuration/examples. Do you have some recommendations for how the defaults could be better?

> I can go on and customise it now (after I figured out why the selected window is squared maybe). Thanks!

Anytime!

**Comment by mauromotion** [comment]
I think a sane default should show most of what is possible to do with the theme. As in, I'd rather start from someone else's customisation than from a blank slate. This is not showing me a good final result that I can possibly achieve with the nice config settings you're giving us. Or maybe, if you'd rather keep a bare bones default for whatever reason, the documentation should be more extensive and with lots of visuals (screenshots) to guide the user. I've just been trying many configs now by throwing the lines in there and reloading. 

Update on the square window that's supposed to be rounded: it gets rounded after I restart tmux completely.

**Comment by davidfmatheson** [comment]
Version 0.4.0 breaks my setup in a way that I can no longer get back, even after cleaning plugins. I new session looks like this:
<img width="254" alt="image" src="https://github.com/user-attachments/assets/f0f3224b-b818-407d-9819-cb7c364a52d1">

when it should have rounded corners and blue 
![image](https://github.com/user-attachments/assets/ecb90ffd-b115-4776-acda-00f6bb039171)

Can we reopen this issue?

**Comment by mauromotion** [comment]
I honestly switched back to nova theme and I customised that with catpuccin colours. This rework of the theme is much appreciated but I found so many other bugs that it's not worth my time. This new implementation doesn't like tpm for some reason, but that's what I use and prefer. I'd say the rework is going well but it's half way through. 

Will come back in a few days. Thanks.

**Comment by kjnsn** [comment]
> when it should have rounded corners and blue 

Would you mind pasting your config?

As a workaround, you can pin to v0.3.0. I'm not sure if you'll get much value from later versions if what you had worked. Is there a reason you wanted to upgrade?


> Can we reopen this issue?

Done! No worries

**Comment by kjnsn** [comment]
> I honestly switched back to nova theme and I customised that with catpuccin colours. This rework of the theme is much appreciated but I found so many other bugs that it's not worth my time. This new implementation doesn't like tpm for some reason, but that's what I use and prefer. I'd say the rework is going well but it's half way through. 
> 
> 
> 
> Will come back in a few days. Thanks.

Please feel free to file issues and I can take a look. Alternatively you can pin to v0.3.0

**Comment by kjnsn** [comment]
Fair enough. If you wanted to use the latest plugin version you would have to rewrite your config like this:

```
# Catppuccin setup
set -g @plugin 'catppuccin/tmux#latest'
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_directory_text "#{pane_current_path}"
set -g @catppuccin_date_time_text "%H:%M"

set -g @plugin 'tmux-plugins/tmux-battery'

set -g status-left "#{@catppuccin_status_session}"
set -g status-right "#{@catppuccin_status_directory}"
set -ag status-right "#{@catppuccin_status_date_time}"
set -ag status-right  "#{@catppuccin_status_battery}"
```

**Comment by davidfmatheson** [comment]
> Fair enough. If you wanted to use the latest plugin version you would have to rewrite your config like this:

Thanks for the config. I tried it and I see the same behavior (non-rounded corners and grey backgrounds).

**Comment by xdannyrobertsx** [comment]
This broke for me yesterday, but was fixed by changing the plugin line to `set -g @plugin 'catppuccin/tmux#tmux-native'`

it looks like it's broken again this morning

**Comment by kjnsn** [comment]
If you'd like to keep on using v0.3.0 you are more than welcome to. It's tagged for a reason :)

Otherwise you will have to migrate your config to be compatible

**Comment by Rasmus-Bertell** [comment]
I have problems with the window separators and pomodoro_plus, everything else seems to work after migration. The options `@catppuccin_window_left_separator` and `@catppuccin_window_right_separator` seem to have no impact. Tested also with all the example configurations and none of them looked like their pictures. Pomodoro status doesn't change and the colors are weird, the plugin `olimorris/tmux-pomodoro-plus` works fine I get notifications of the status changes but they are not reflected in tmux status bar.

I'm currently running tmux inside WSL but I'll report how it works on native linux once I get around to updating my other computer.

![image](https://github.com/user-attachments/assets/7a698c8e-7a6a-422d-bbff-c9c5721651e6)
![image](https://github.com/user-attachments/assets/5a0e078a-61d5-43f7-8d9c-c75652d7dca2)

My config:

```tmux
#...
set-option -g @plugin 'catppuccin/tmux'
set-option -g @plugin 'olimorris/tmux-pomodoro-plus'
#...

# Catppuccin options
set-option -g @catppuccin_flavor 'latte'

set-option -g @catppuccin_window_left_separator ""
set-option -g @catppuccin_window_right_separator " "

set-option -g @catppuccin_window_default_text "#W"
set-option -g @catppuccin_window_current_text "#W"

set-option -g @catppuccin_status_modules_right "pomodoro_plus application directory user host session"
set-option -g @catppuccin_status_left_separator  ""
set-option -g @catppuccin_status_right_separator ""
set-option -g @catppuccin_status_connect_separator "no"

set-option -g @catppuccin_directory_text "#{pane_current_path}"

set-option -g  status-right "#{E:@catppuccin_status_pomodoro_plus}"
set-option -ag status-right " #{E:@catppuccin_status_kube}"
set-option -ag status-right " #{E:@catppuccin_status_application}"
set-option -ag status-right " #{E:@catppuccin_status_directory}"
set-option -ag status-right " #{E:@catppuccin_status_user}"
set-option -ag status-right " #{E:@catppuccin_status_host}"
set-option -ag status-right " #{E:@catppuccin_status_session}"

# Pomodoro Plus options
set-option -g @pomodoro_on              '󰐊 '
set-option -g @pomodoro_complete        '󰶞 '
set-option -g @pomodoro_pause           '󰏤 '

set-option -g @pomodoro_prompt_break    'break?'
set-option -g @pomodoro_prompt_pomodoro 'start?'

set-option -g @pomodoro_long_break_mins 15

set-option -g @pomodoro_notifications 'on'

#...

run '~/.config/tmux/plugins/tpm/tpm'
```

**Comment by Rasmus-Bertell** [comment]
Figured out why window styles weren't working. I had to define `@catppuccin_window_status_style` as stated in https://github.com/catppuccin/tmux/tree/main?tab=readme-ov-file#window. Should also be reflected in the example configs because they don't work without it and in the migration guide.

Also figured out how to get rid of the session title next to the windows by defining 

```tmux
set-option -g status-left ""
```

This just leaves me with the pomodoro plus plugin which doesn't work at all but I can open a separate issue for that.

**Comment by kjnsn** [comment]
If you're happy to create a separate issue for pomodoro that would be great!
